### ISSUE TITLE
Error when trying to download checkpoint.pth

### ISSUE THREAD

**Issue by CH-901** [bytedance/particle-sfm#17]
When I access this link [http://b1ueber2y.me/ParticleSfM/checkpoint.pth],  the following prompt appears:
![image](https://github.com/bytedance/particle-sfm/assets/40879379/191f32d6-e64a-4fde-8042-a4cc0afb0aed)

I think this link may be invalid. Can you put the pre trained model on Google Cloud Drive? Thank you!
@guohengkai

**Comment by B1ueber2y** [comment]
Hey. The link is on ftp server so you cannot browse it in this way. I just tried the "wget" again and it worked very well.

Nonetheless, I just uploaded to Google drive as well. Here is the link: https://drive.google.com/file/d/1AfhRB6DlWdtPCkfXRJPMhG29KOzmWNwT/view

Thanks!

**Comment by CH-901** [comment]
Thanks！ My server is unable to connect to the internet and cannot use “wget”, so I can only download it offline. Your Google drive link is working, thank you again！
