### ISSUE TITLE
missing header in TheiaSfm

### ISSUE THREAD

**Issue by Lwy-1998** [bytedance/particle-sfm#21]
i got a problem when building Theiasfm under custom branch.
which shows
`/home/xxx/TheiaSfM/src/theia/io/write_calibration_test.cc:45:14: error: expected constructor, destructor, or type conversion before ‘(’ token
   45 | DEFINE_string(json_file, "io/write_calibration_test.json",
      |              ^
/home/xxx/TheiaSfM/src/theia/io/read_calibration_test.cc:43:14: error: expected constructor, destructor, or type conversion before ‘(’ token
   43 | DEFINE_string(json_file, "io/calibration_test.json");
      |              ^
/home/xxx/TheiaSfM/src/theia/io/write_calibration_test.cc:51:65: error: ‘FLAGS_json_file’ was not declared in this scope
   51 | std::string json_filepath = THEIA_DATA_DIR + std::string("/") + FLAGS_json_file;
      |                                                                 ^~~~~~~~~~~~~~~
/home/xxx/TheiaSfM/src/theia/io/read_calibration_test.cc:48:65: error: ‘FLAGS_json_file’ was not declared in this scope
   48 | std::string json_filepath = THEIA_DATA_DIR + std::string("/") + FLAGS_json_file;
      |                 `

I fix this problem by simply adding `#include <gflags/gflags.h>` to `read_calibration_test` and `write_calibration_test` 

I Hope this can help.

**Comment by guohengkai** [comment]
Thank you for your information.
