### ISSUE TITLE
Segmentation Fault (Core Dumped)

### ISSUE THREAD

**Issue by cho-wang001** [bytedance/particle-sfm#27]
Hi 

Thank you so much for the great work. I am always facing this error while running particlesfm.

A total of 20 sequences found in /home/zhuo/particle-sfm/rr/.
[ParticleSFM] Running pairwise optical flow inference......
/home/zhuo/anaconda3/envs/particlesfm/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729006826/work/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Loading weights:  /home/zhuo/particle-sfm/third_party/RAFT/models/raft-things.pth
100%|█████████████████████████████████████████████| 2/2 [03:19<00:00, 99.80s/it]
[ParticleSfM] Running pairwise optical flow inference (stride 2)......
Loading weights:  /home/zhuo/particle-sfm/third_party/RAFT/models/raft-things.pth
100%|█████████████████████████████████████████████| 1/1 [01:19<00:00, 79.64s/it]
[ParticleSfM] Connecting (optimization enabled) point trajectories from optical flows.......
/home/zhuo/particle-sfm/rr/scene0707_00/optical_flows/flow_f2
  5%|██▏                                         | 1/20 [00:06<02:03,  6.50s/it]Segmentation fault (core dumped)

**Comment by guohengkai** [comment]
Hi, this is the issue about your GPU driver. It is nothing to do with our repo. Please test the following codes:
```python
import torch
x = torch.rand(5, 3).cuda()
print(x)
```
See https://stackoverflow.com/questions/54264338/why-does-pytorch-not-find-my-nvdia-drivers-for-cuda-support or https://discuss.pytorch.org/t/found-no-nvidia-driver-on-your-system-but-its-there/35063 to find some possible solutions.

**Comment by C-H-Chien** [comment]
Hi, I made some minor revisions on the code to enforce everything run on CPU, and I met the same issue.
Is your code only doable on GPU? Thanks.

**Comment by guohengkai** [comment]
@C-H-Chien It is nothing to do with the GPU driver in trajectory optimization. Maybe we can open a new issue to discuss it. BTW, we haven't tested the CPU version yet.

**Comment by guohengkai** [comment]
@C-H-Chien Some suggestions:

**Comment by guohengkai** [comment]
@C-H-Chien Some suggestions:
1. Disable the trajectory optimization to test if all the other part works normally. (--skip_path_consistency)
2. Print the inputs of the trajectory optimization to check if something goes wrong.
3. Check the flow outputs after you modify it to CPU mode.
