### ISSUE TITLE
are you using G.T camera intrinsics?

### ISSUE THREAD

**Issue by fangli333** [bytedance/particle-sfm#30]

**Comment by guohengkai** [comment]
No. The camera intrinsics are jointly optimized by SfM.

**Comment by liufanfanliu** [comment]
> No. The camera intrinsics are jointly optimized by SfM.

the camera distortion parameters also will be optimized by SFM?

**Comment by guohengkai** [comment]
@liufanfanliu https://github.com/bytedance/particle-sfm/blob/main/sfm/import_feature_matches.py#L57
The camera type is set to pinhole so there are no distortion parameters.

**Comment by liufanfanliu** [comment]
> @liufanfanliu https://github.com/bytedance/particle-sfm/blob/main/sfm/import_feature_matches.py#L57 The camera type is set to pinhole so there are no distortion parameters.

If I changed the camera model with distoration params, it can also be optimized ?
