### ISSUE TITLE
Error when trying to download checkpoint.pth

### ISSUE THREAD

**Issue by drorsimon** [bytedance/particle-sfm#9]
Hi!
I tried running
`bash scripts/download_all_models.sh`

But I am getting:
`--2022-12-21 13:01:20--  ftp://b1ueber2y.me/ParticleSfM/checkpoint.pth
  (try: 3) => './motion_seg/log/pretrain/checkpoint.pth'
Connecting to b1ueber2y.me (b1ueber2y.me)|93.179.103.61|:21... connected.
Error in server response. Closing.
Retrying.`

**Comment by CH-901** [comment]
Hi @drorsimon  , it seems that this link is no longer valid. Could you please send me a copy? Thank you
